services:
  db:
    container_name: mysql_pttk
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pttk
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    restart: always
